version: '3.7'

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: '14.17.4'
      target: development
    image: paprika:1.0.0
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    working_dir: /app
    command: npm start
    environment:
      HISTFILE: /app/log/.bash_history
      LOG: ''
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - .:/app:cached
    ports:
      - "8000:8000"
